import path from "node:path";

export function safeKey(value){
  const key=String(value||"").toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,63);
  if(!/^[a-z0-9][a-z0-9-]*$/.test(key)) throw new Error("Could not derive safe project key");
  return key;
}

export function projectEntry({projectKey,repository,defaultBranch="main",validationProfile,enabled=true}){
  const allowed=[...new Set(["git",...(validationProfile?.allowed_executables||[])])];
  return {
    key:projectKey,
    value:{
      repository,
      enabled:Boolean(enabled),
      default_branch:defaultBranch,
      checkpoint_branch:"codex/checkpoints",
      local_path_key:projectKey,
      default_review_route:projectKey,
      allowed_validation_executables:allowed,
      default_validation_steps:validationProfile?.validation_steps||[],
      prompt_limits:{initial_max_chars:12000,revise_max_chars:6000},
      enforce_wrapper_validation:true,
      max_iterations:5,
      code_review:{
        enabled:true,
        required_for_code_changes:true,
        review_model:"gpt-5.6-luna",
        review_reasoning:"medium",
        docs_only_skip:true
      }
    }
  };
}

export function renderProjectsRegistry(entries){
  const projects={};
  for(const entry of entries){
    if(!entry?.key||projects[entry.key]) throw new Error("Duplicate or invalid project entry");
    projects[entry.key]=entry.value;
  }
  return JSON.stringify({projects},null,2)+"\n";
}

export function renderProjectsJson(args){
  return renderProjectsRegistry([projectEntry(args)]);
}

function psQuote(value){
  return "'" + String(value).replaceAll("'","''") + "'";
}

export function renderConfigPs1({githubLogin,projectKey,projectClonePath,reviewerChatUrl,projectMappings,runnerPath,browserPort,browserProfile}){
  const mappings=projectMappings?.length
    ? projectMappings
    : [{projectKey,projectClonePath,reviewerChatUrl}];

  const localLines=mappings.map(x=>"  "+psQuote(x.projectKey)+" = "+psQuote(x.projectClonePath));
  const routeLines=mappings.map(x=>"  "+psQuote(x.projectKey)+" = "+psQuote(x.reviewerChatUrl));

  return [
    "# Generated by ChatGPT Codex Orchestrator. Do not commit this file.",
    "$TRUSTED_GITHUB_USERS = @("+psQuote(githubLogin)+")",
    "",
    "$PROJECT_LOCAL_PATHS = @{",
    ...localLines,
    "}",
    "",
    "$PROJECT_REVIEW_ROUTES = @{",
    ...routeLines,
    "}",
    "",
    "$CHAT_ROUTES = @{}",
    "",
    "$env:ORCHESTRATOR_BROWSER_DEBUG_PORT = "+psQuote(String(browserPort)),
    "$env:ORCHESTRATOR_BROWSER_PROFILE = "+psQuote(browserProfile),
    "$env:ORCHESTRATOR_ORIGIN_FALLBACK_MINUTES = '30'",
    "$env:ORCHESTRATOR_INSTANCE_ID = "+psQuote(path.basename(runnerPath)),
    "$env:CODEX_ORCHESTRATOR_MODEL = 'gpt-5.6-luna'",
    "$env:CODEX_ORCHESTRATOR_REASONING = 'low'",
    "$env:CODEX_ORCHESTRATOR_RUNNER_PATH = "+psQuote(runnerPath),
    ""
  ].join("\n");
}

export function renderWorkflow(template,{runnerLabel}){
  if(!/^[A-Za-z0-9._-]{1,64}$/.test(runnerLabel)) throw new Error("Invalid runner label");
  return String(template).replaceAll("{{RUNNER_LABEL}}",runnerLabel);
}

export function defaultLocalPaths({home,installationId,projectKey}){
  const short=String(installationId).replace(/[^A-Za-z0-9]/g,"").slice(0,8)||"default";
  return {
    control:path.join(home,"ChatGPTCodexOrchestrator","control-"+short),
    project:path.join(home,"ChatGPTCodexProjects",projectKey),
    runner:path.join(home,"ChatGPTCodexOrchestrator","runner-"+short),
    runnerLabel:"codex-orchestrator-"+short.toLowerCase()
  };
}
