export const ERROR_CATALOG={
  "SETUP-001":"Git installation failed or Git is unavailable.",
  "SETUP-002":"Node.js installation failed or Node.js is unavailable.",
  "SETUP-003":"Codex CLI installation failed.",
  "SETUP-004":"Required local prerequisite is unavailable after bootstrap.",
  "SETUP-005":"Repository answer is invalid.",
  "SETUP-006":"Reviewer Chat URL is invalid.",
  "SETUP-007":"Project Instructions confirmation is invalid.",
  "SETUP-008":"Sandbox verification confirmation is invalid.",
  "SETUP-009":"Installer action is unknown.",
  "SETUP-010":"GitHub CLI installation failed or GitHub CLI is unavailable.",
  "SETUP-011":"Private control environment setup failed.",
  "SETUP-012":"Reviewer browser sign-in was not confirmed.",
  "SETUP-013":"Verified target project activation failed after sandbox validation.",
  "AUTH-001":"GitHub authorization is missing.",
  "AUTH-002":"Codex login is unavailable.",
  "AUTH-003":"GitHub CLI login is unavailable.",
  "AUTH-004":"Requested Codex trust folder is unavailable.",
  "RUN-001":"Automation runner is offline.",
  "RUN-002":"Repository mapping does not match the configured project.",
  "CODEX-001":"Codex execution failed.",
  "CODEX-002":"Prompt was rejected before Codex execution.",
  "CALLBACK-001":"Reviewer Chat was not found.",
  "CALLBACK-002":"Chat composer was not found.",
  "CALLBACK-003":"Callback text reached ChatGPT but submission was not confirmed.",
  "CALLBACK-004":"Callback was queued for retry.",
  "REVIEW-001":"Independent Codex review command is unavailable.",
  "REVIEW-002":"Requested reviewed commit became stale.",
  "MERGE-001":"Approved commit does not match the branch head.",
  "MERGE-002":"Required code-review evidence is missing.",
  "DOCTOR-001":"One or more health checks require attention.",
  "REPAIR-001":"Automatic runtime repair failed or is not ready.",
  "SANDBOX-001":"Sandbox smoke test could not start or be inspected.",
  "SANDBOX-002":"Sandbox implementation or validation failed.",
  "SANDBOX-003":"Sandbox Code Review request failed.",
  "SANDBOX-004":"Explicit sandbox merge approval was not supplied.",
  "SANDBOX-005":"Sandbox merge approval request failed.",
  "REPORT-001":"Diagnostic upload consent was not provided.",
  "REPORT-002":"Diagnostic report file is missing.",
  "REPORT-003":"Feedback repository is not configured.",
  "REPORT-004":"Diagnostic submission failed."
};
