import fs from "node:fs";
import {spawnSafeSync} from "./spawn-safe.mjs";

export function submitDiagnosticReport({file,repository}){
  if(!fs.existsSync(file)) throw new Error("Diagnostic report file does not exist");
  if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repository)) throw new Error("Invalid feedback repository");

  const report=JSON.parse(fs.readFileSync(file,"utf8"));
  const errorId=String(report.last_error?.error_id||report.error_id||"UNCLASSIFIED").replace(/[^A-Za-z0-9._-]/g,"");
  const title="[Bug] "+errorId;

  const body=[
    "## What happened",
    "",
    "A sanitised diagnostic report was submitted with explicit user consent.",
    "",
    "## Diagnostic report",
    "",
    "~~~json",
    JSON.stringify(report,null,2),
    "~~~",
    "",
    "## Privacy",
    "",
    "The report was generated by the local sanitiser before submission."
  ].join("\n");

  const temp=file+".issue.md";
  fs.writeFileSync(temp,body);
  try{
    const r=spawnSafeSync("gh",["issue","create","--repo",repository,"--title",title,"--body-file",temp],{
      encoding:"utf8",
    });
    if(r.status!==0) throw new Error((r.stderr||r.stdout||"GitHub issue submission failed").trim());
    const output=(r.stdout||"").trim();
    const url=output.split(/\s+/).find(x=>/^https:\/\/github\.com\//.test(x))||null;
    return {url,output};
  }finally{
    fs.rmSync(temp,{force:true});
  }
}
